# Generated by Django 3.1.3 on 2021-01-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210113_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='finish_time',
            field=models.DateField(null=True),
        ),
    ]
