# Generated by Django 3.1.3 on 2021-01-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210113_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CMPD', 'COMPLETED'), ('WTNG', 'WAITING'), ('CNLD', 'CANCELED')], default='WTNG', max_length=4),
        ),
    ]
