# Generated by Django 3.1.3 on 2021-01-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210113_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.CharField(choices=[('DEAD', 'DEAD'), ('ALV', 'ALIVE')], default='ALV', max_length=4),
        ),
    ]
