# Generated by Django 3.1.3 on 2021-01-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='purchased',
        ),
    ]
